//Even Fibonacci numbers
//Problem 2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



var num1 = 1
var num2 = 2
var active = 2
var total = 0

while (active <= 4000000)
{
  if (active % 2 === 0)
     total += active;
     active = num1 + num2;
     num1 = num2;
     num2 = active;
}
console.log(total);